version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "audio-event-detection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11svigbf8xjsi"
s3_prefix = "audio-event-detection"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
