AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Resources:
  conductor:
    Type: AWS::Serverless::Function
    Properties:
      Description: Initiates audio event detection worker instances
      Handler: main.handler
      Runtime: python3.7
      CodeUri: functions/conductor
      AutoPublishAlias: ${ALIAS}
      MemorySize: 512
      Timeout: 600
      Role: arn:aws:iam::584765855847:role/service-role/SieveLambda
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      VpcConfig:
        SecurityGroupIds:
          - sg-0d6bbaa8d86af7842
        SubnetIds:
          - subnet-0c8a25e65ccd76b26
          - subnet-0d5b504a641e86d5d
      Environment:
        Variables:
          AWS_SECRET: ${AWS_SECRET}
          SQS_QUEUE: audio-event-detection-staging
          SQS_QUEUE_LARGE: audio-event-detection-staging-large
      Layers:
        - arn:aws:lambda:us-east-1:584765855847:layer:sqlalchemy:1
  worker:
    Type: AWS::Serverless::Function
    Properties:
      Description: Detects audio events in a batch of recordings
      Handler: aed_batch.handler
      Runtime: python3.7
      CodeUri: functions/worker
      AutoPublishAlias: ${ALIAS}
      MemorySize: 1024
      Timeout: 900
      Role: arn:aws:iam::584765855847:role/service-role/SieveLambda
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue: ${QUEUE}
            BatchSize: 1
      Environment:
        Variables:
          AWS_SECRET: ${AWS_SECRET}
          RECBUCKET: ${AWS_AUDIO_BUCKET_SIEVE}
          WRITEBUCKET: arbimon2
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:115
        - arn:aws:lambda:us-east-1:584765855847:layer:scikit-image:15
        - arn:aws:lambda:us-east-1:584765855847:layer:libsndfile-slim:1
        - arn:aws:lambda:us-east-1:584765855847:layer:sqlalchemy_test:1
      ReservedConcurrentExecutions: 1
  workerLarge:
    Type: AWS::Serverless::Function
    Properties:
      Description: Detects audio events in a batch of recordings
      Handler: aed_batch.handler
      Runtime: python3.7
      CodeUri: functions/worker
      AutoPublishAlias: ${ALIAS}
      MemorySize: 1024
      Timeout: 900
      Role: arn:aws:iam::584765855847:role/service-role/SieveLambda
      EventInvokeConfig:
        MaximumRetryAttempts: 0
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue: ${QUEUE_LARGE}
            BatchSize: 1
      Environment:
        Variables:
          AWS_SECRET: ${AWS_SECRET}
          RECBUCKET: ${AWS_AUDIO_BUCKET_SIEVE}
          WRITEBUCKET: arbimon2
      Layers:
        - arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:115
        - arn:aws:lambda:us-east-1:584765855847:layer:scikit-image:15
        - arn:aws:lambda:us-east-1:584765855847:layer:libsndfile-slim:1
        - arn:aws:lambda:us-east-1:584765855847:layer:sqlalchemy_test:1
      ReservedConcurrentExecutions: 1

